USE `cv_builder`;

-- ============================================================
-- INDUSTRIES (20)
-- ============================================================
INSERT INTO `industries` (`name`, `slug`, `icon`, `sort_order`) VALUES
('Technology', 'technology', 'laptop-code', 1),
('Healthcare', 'healthcare', 'heart-pulse', 2),
('Finance & Banking', 'finance-banking', 'chart-line', 3),
('Education', 'education', 'graduation-cap', 4),
('Marketing & Advertising', 'marketing-advertising', 'bullhorn', 5),
('Sales', 'sales', 'handshake', 6),
('Engineering', 'engineering', 'gears', 7),
('Human Resources', 'human-resources', 'users', 8),
('Legal', 'legal', 'scale-balanced', 9),
('Hospitality & Tourism', 'hospitality-tourism', 'bell-concierge', 10),
('Real Estate', 'real-estate', 'house', 11),
('Manufacturing', 'manufacturing', 'industry', 12),
('Retail', 'retail', 'cart-shopping', 13),
('Media & Entertainment', 'media-entertainment', 'film', 14),
('Non-Profit', 'non-profit', 'hand-holding-heart', 15),
('Government', 'government', 'landmark', 16),
('Construction', 'construction', 'helmet-safety', 17),
('Transportation & Logistics', 'transportation-logistics', 'truck', 18),
('Agriculture', 'agriculture', 'wheat-awn', 19),
('Consulting', 'consulting', 'briefcase', 20);

-- ============================================================
-- CV TEMPLATES (15)
-- ============================================================
INSERT INTO `cv_templates` (`name`, `slug`, `description`, `category`, `html_structure`, `css_styles`, `sort_order`) VALUES
('Modern', 'modern', 'Two-column layout with accent color sidebar, perfect for tech and startup professionals.', 'professional',
'<div class="cv-modern"><div class="sidebar"><div class="profile-photo">{{photo}}</div><h1>{{first_name}} {{last_name}}</h1><p class="job-title">{{job_title}}</p><div class="contact-info">{{contact_entries}}</div><div class="skills-section"><h3>Skills</h3>{{skills_entries}}</div><div class="languages-section"><h3>Languages</h3>{{language_entries}}</div></div><div class="main-content"><div class="summary-section"><h2>Professional Summary</h2><p>{{summary}}</p></div><div class="experience-section"><h2>Experience</h2>{{experience_entries}}</div><div class="education-section"><h2>Education</h2>{{education_entries}}</div><div class="certifications-section"><h2>Certifications</h2>{{certification_entries}}</div></div></div>',
'.cv-modern{display:flex;font-family:"Segoe UI",Tahoma,sans-serif;max-width:900px;margin:0 auto;min-height:1100px}.cv-modern .sidebar{width:32%;background:#2c3e50;color:#fff;padding:30px 20px}.cv-modern .sidebar .profile-photo{width:120px;height:120px;border-radius:50%;border:4px solid #3498db;margin:0 auto 20px;background:#34495e;display:flex;align-items:center;justify-content:center;font-size:40px}.cv-modern .sidebar h1{font-size:22px;text-align:center;margin-bottom:5px}.cv-modern .sidebar .job-title{text-align:center;color:#3498db;font-size:14px;margin-bottom:25px}.cv-modern .sidebar .contact-info{font-size:12px;line-height:2}.cv-modern .sidebar h3{font-size:14px;border-bottom:2px solid #3498db;padding-bottom:5px;margin-bottom:10px;color:#3498db}.cv-modern .sidebar .skill-item{background:#34495e;padding:5px 10px;margin:4px 0;border-radius:3px;font-size:12px}.cv-modern .main-content{width:68%;padding:30px}.cv-modern .main-content h2{font-size:18px;color:#2c3e50;border-bottom:2px solid #3498db;padding-bottom:5px;margin-bottom:15px}.cv-modern .main-content .summary-section{margin-bottom:20px;font-size:14px;line-height:1.6}.cv-modern .experience-entry,.cv-modern .education-entry{margin-bottom:15px}.cv-modern .entry-title{font-weight:bold;font-size:15px}.cv-modern .entry-company{color:#3498db;font-size:13px}.cv-modern .entry-date{color:#7f8c8d;font-size:12px}.cv-modern .entry-description{font-size:13px;line-height:1.5;margin-top:5px}',
1),

('Classic', 'classic', 'Traditional single-column layout with serif fonts, ideal for corporate and finance.', 'professional',
'<div class="cv-classic"><header><h1>{{first_name}} {{last_name}}</h1><div class="contact-line">{{contact_entries}}</div></header><div class="summary-section"><h2>Professional Summary</h2><p>{{summary}}</p></div><div class="experience-section"><h2>Professional Experience</h2>{{experience_entries}}</div><div class="education-section"><h2>Education</h2>{{education_entries}}</div><div class="skills-section"><h2>Skills</h2>{{skills_entries}}</div><div class="certifications-section"><h2>Certifications</h2>{{certification_entries}}</div></div>',
'.cv-classic{font-family:Georgia,"Times New Roman",serif;max-width:800px;margin:0 auto;padding:40px;color:#333}.cv-classic header{text-align:center;border-bottom:2px solid #333;padding-bottom:20px;margin-bottom:25px}.cv-classic header h1{font-size:28px;letter-spacing:2px;margin-bottom:8px;text-transform:uppercase}.cv-classic header .contact-line{font-size:13px;color:#555}.cv-classic h2{font-size:16px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #999;padding-bottom:5px;margin:20px 0 12px;color:#222}.cv-classic .summary-section{font-size:14px;line-height:1.7;margin-bottom:20px}.cv-classic .experience-entry,.cv-classic .education-entry{margin-bottom:18px}.cv-classic .entry-header{display:flex;justify-content:space-between}.cv-classic .entry-title{font-weight:bold;font-size:15px}.cv-classic .entry-date{font-style:italic;color:#666;font-size:13px}.cv-classic .entry-company{font-size:14px;color:#555}.cv-classic .entry-description{font-size:13px;line-height:1.6;margin-top:5px}.cv-classic .skill-list{display:flex;flex-wrap:wrap;gap:8px}.cv-classic .skill-item{background:#f0f0f0;padding:4px 12px;font-size:12px;border-radius:2px}',
2),

('Minimal', 'minimal', 'Clean design with generous whitespace and modern sans-serif typography.', 'minimal',
'<div class="cv-minimal"><header><h1>{{first_name}} {{last_name}}</h1><p class="tagline">{{job_title}}</p><div class="contact">{{contact_entries}}</div></header><section class="summary"><p>{{summary}}</p></section><section class="experience"><h2>Experience</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="skills"><h2>Skills</h2>{{skills_entries}}</section></div>',
'.cv-minimal{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;max-width:750px;margin:0 auto;padding:50px 40px;color:#1a1a1a}.cv-minimal header{margin-bottom:40px}.cv-minimal header h1{font-size:32px;font-weight:300;letter-spacing:-0.5px;margin-bottom:5px}.cv-minimal header .tagline{font-size:16px;color:#888;font-weight:300;margin-bottom:10px}.cv-minimal header .contact{font-size:13px;color:#666}.cv-minimal h2{font-size:11px;text-transform:uppercase;letter-spacing:3px;color:#999;margin:30px 0 15px;font-weight:500}.cv-minimal .summary{font-size:15px;line-height:1.8;color:#444}.cv-minimal .experience-entry,.cv-minimal .education-entry{margin-bottom:25px}.cv-minimal .entry-title{font-size:16px;font-weight:500;margin-bottom:2px}.cv-minimal .entry-company{font-size:14px;color:#666}.cv-minimal .entry-date{font-size:12px;color:#aaa;margin-bottom:5px}.cv-minimal .entry-description{font-size:14px;line-height:1.7;color:#444}.cv-minimal .skill-item{display:inline-block;font-size:13px;color:#555;margin-right:15px;margin-bottom:5px}',
3),

('Creative', 'creative', 'Bold headers and colorful visual elements for marketing and creative professionals.', 'creative',
'<div class="cv-creative"><div class="header-banner"><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p><div class="contact-bar">{{contact_entries}}</div></div><div class="content-grid"><div class="left-col"><section class="summary"><h2>About Me</h2><p>{{summary}}</p></section><section class="experience"><h2>Experience</h2>{{experience_entries}}</section></div><div class="right-col"><section class="skills"><h2>Skills</h2>{{skills_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="languages"><h2>Languages</h2>{{language_entries}}</section></div></div></div>',
'.cv-creative{font-family:"Poppins",sans-serif;max-width:850px;margin:0 auto;overflow:hidden}.cv-creative .header-banner{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;padding:40px;text-align:center}.cv-creative .header-banner h1{font-size:36px;font-weight:700;margin-bottom:5px}.cv-creative .header-banner .title{font-size:18px;opacity:0.9;margin-bottom:10px}.cv-creative .header-banner .contact-bar{font-size:13px;opacity:0.8}.cv-creative .content-grid{display:grid;grid-template-columns:2fr 1fr;gap:0}.cv-creative .left-col{padding:30px}.cv-creative .right-col{background:#f8f9fa;padding:30px}.cv-creative h2{font-size:16px;color:#764ba2;margin-bottom:12px;position:relative;padding-left:15px}.cv-creative h2::before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:linear-gradient(to bottom,#667eea,#764ba2);border-radius:2px}.cv-creative .summary{margin-bottom:25px;font-size:14px;line-height:1.7}.cv-creative .experience-entry{margin-bottom:20px;padding-left:15px;border-left:3px solid #667eea}.cv-creative .entry-title{font-weight:600;font-size:15px}.cv-creative .entry-company{color:#667eea;font-size:13px}.cv-creative .entry-date{color:#999;font-size:12px}.cv-creative .entry-description{font-size:13px;line-height:1.6;margin-top:5px}.cv-creative .skill-item{background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;padding:5px 12px;margin:4px;border-radius:20px;font-size:12px;display:inline-block}',
4),

('Executive', 'executive', 'Formal and authoritative design for C-suite and senior management roles.', 'executive',
'<div class="cv-executive"><header><div class="name-block"><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p></div><div class="contact-strip">{{contact_entries}}</div></header><section class="summary"><h2>Executive Profile</h2><p>{{summary}}</p></section><section class="experience"><h2>Professional Experience</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="certifications"><h2>Board Memberships & Certifications</h2>{{certification_entries}}</section></div>',
'.cv-executive{font-family:"Palatino Linotype","Book Antiqua",Palatino,serif;max-width:800px;margin:0 auto;padding:0;color:#1a1a1a}.cv-executive header{background:#1a1a2e;color:#fff;padding:35px 40px}.cv-executive header h1{font-size:30px;letter-spacing:1px;margin-bottom:5px}.cv-executive header .title{font-size:16px;color:#c9a227;font-weight:400;letter-spacing:2px;text-transform:uppercase}.cv-executive header .contact-strip{margin-top:15px;font-size:12px;color:#ccc;display:flex;gap:20px;flex-wrap:wrap}.cv-executive h2{font-size:14px;text-transform:uppercase;letter-spacing:3px;color:#1a1a2e;border-bottom:2px solid #c9a227;padding-bottom:8px;margin:25px 0 15px}.cv-executive .summary{padding:30px 40px;font-size:15px;line-height:1.8;color:#333}.cv-executive .experience-entry,.cv-executive .education-entry{padding:0 40px;margin-bottom:20px}.cv-executive .entry-title{font-size:17px;font-weight:700}.cv-executive .entry-company{font-size:14px;color:#c9a227}.cv-executive .entry-date{font-size:12px;color:#888;margin-bottom:5px}.cv-executive .entry-description{font-size:14px;line-height:1.7;color:#444}.cv-executive .skill-item{font-size:13px;padding:3px 0;border-bottom:1px solid #eee}',
5),

('Academic', 'academic', 'Detailed layout with emphasis on publications, research, and academic achievements.', 'academic',
'<div class="cv-academic"><header><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p><div class="contact">{{contact_entries}}</div></header><section class="summary"><h2>Research Interests</h2><p>{{summary}}</p></section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="experience"><h2>Academic Appointments</h2>{{experience_entries}}</section><section class="publications"><h2>Publications</h2>{{publication_entries}}</section><section class="certifications"><h2>Grants & Fellowships</h2>{{certification_entries}}</section><section class="skills"><h2>Research Skills</h2>{{skills_entries}}</section></div>',
'.cv-academic{font-family:"Times New Roman",serif;max-width:850px;margin:0 auto;padding:40px;color:#222}.cv-academic header{text-align:center;border-bottom:3px double #333;padding-bottom:20px;margin-bottom:25px}.cv-academic header h1{font-size:26px;margin-bottom:5px}.cv-academic header .title{font-style:italic;font-size:15px;color:#444;margin-bottom:8px}.cv-academic header .contact{font-size:13px;color:#555}.cv-academic h2{font-size:15px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #333;padding-bottom:5px;margin:22px 0 12px}.cv-academic .summary{font-size:14px;line-height:1.8}.cv-academic .experience-entry,.cv-academic .education-entry{margin-bottom:15px}.cv-academic .entry-title{font-weight:bold;font-size:14px}.cv-academic .entry-company{font-style:italic;font-size:13px;color:#444}.cv-academic .entry-date{font-size:12px;color:#666}.cv-academic .entry-description{font-size:13px;line-height:1.6;margin-top:4px}.cv-academic .skill-item{font-size:13px;display:inline-block;margin-right:12px}',
6),

('Technical', 'technical', 'Skills-focused structured layout ideal for engineering and IT professionals.', 'professional',
'<div class="cv-technical"><header><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p><div class="contact">{{contact_entries}}</div></header><section class="summary"><h2>Technical Summary</h2><p>{{summary}}</p></section><section class="skills"><h2>Technical Skills</h2>{{skills_entries}}</section><section class="experience"><h2>Work Experience</h2>{{experience_entries}}</section><section class="projects"><h2>Key Projects</h2>{{project_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="certifications"><h2>Certifications</h2>{{certification_entries}}</section></div>',
'.cv-technical{font-family:"Consolas","Courier New",monospace;max-width:850px;margin:0 auto;padding:30px;color:#2d2d2d;background:#fafafa}.cv-technical header{border-left:4px solid #0066cc;padding-left:20px;margin-bottom:25px}.cv-technical header h1{font-size:24px;color:#0066cc;margin-bottom:3px}.cv-technical header .title{font-size:14px;color:#555}.cv-technical header .contact{font-size:12px;color:#777;margin-top:5px}.cv-technical h2{font-size:14px;color:#0066cc;border-bottom:1px dashed #0066cc;padding-bottom:5px;margin:20px 0 12px;text-transform:uppercase}.cv-technical .summary{font-size:13px;line-height:1.7;margin-bottom:15px}.cv-technical .skill-category{margin-bottom:10px}.cv-technical .skill-category-name{font-weight:bold;font-size:13px;color:#333}.cv-technical .skill-list{font-size:12px;color:#555;margin-left:15px}.cv-technical .experience-entry{margin-bottom:18px;padding-left:15px;border-left:2px solid #ddd}.cv-technical .entry-title{font-weight:bold;font-size:14px}.cv-technical .entry-company{color:#0066cc;font-size:13px}.cv-technical .entry-date{font-size:11px;color:#888}.cv-technical .entry-description{font-size:12px;line-height:1.6;margin-top:4px}',
7),

('Infographic', 'infographic', 'Visual layout with charts, icons, and modern design elements.', 'creative',
'<div class="cv-infographic"><div class="top-section"><div class="profile-area"><div class="avatar">{{photo}}</div><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p></div><div class="contact-area">{{contact_entries}}</div></div><div class="body-section"><div class="col-main"><section class="summary"><h2>Profile</h2><p>{{summary}}</p></section><section class="experience"><h2>Experience</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section></div><div class="col-side"><section class="skills"><h2>Skills</h2>{{skills_entries}}</section><section class="languages"><h2>Languages</h2>{{language_entries}}</section><section class="interests"><h2>Interests</h2>{{interest_entries}}</section></div></div></div>',
'.cv-infographic{font-family:"Montserrat",sans-serif;max-width:850px;margin:0 auto;overflow:hidden}.cv-infographic .top-section{background:linear-gradient(135deg,#f093fb 0%,#f5576c 100%);color:#fff;padding:35px;display:flex;align-items:center;gap:25px}.cv-infographic .profile-area .avatar{width:100px;height:100px;border-radius:50%;background:rgba(255,255,255,0.2);display:flex;align-items:center;justify-content:center;font-size:36px;border:3px solid rgba(255,255,255,0.5)}.cv-infographic .profile-area h1{font-size:28px;font-weight:700;margin-bottom:3px}.cv-infographic .profile-area .title{font-size:14px;opacity:0.9}.cv-infographic .contact-area{margin-left:auto;font-size:12px;text-align:right;line-height:2}.cv-infographic .body-section{display:grid;grid-template-columns:65% 35%}.cv-infographic .col-main{padding:25px}.cv-infographic .col-side{background:#f8f9fa;padding:25px}.cv-infographic h2{font-size:13px;text-transform:uppercase;letter-spacing:2px;color:#f5576c;margin-bottom:12px}.cv-infographic .summary{font-size:14px;line-height:1.7;margin-bottom:20px}.cv-infographic .experience-entry{margin-bottom:15px}.cv-infographic .entry-title{font-weight:600;font-size:14px}.cv-infographic .entry-company{color:#f5576c;font-size:13px}.cv-infographic .entry-date{font-size:11px;color:#999}.cv-infographic .entry-description{font-size:13px;line-height:1.6}.cv-infographic .skill-bar{margin-bottom:10px}.cv-infographic .skill-name{font-size:12px;margin-bottom:3px}.cv-infographic .skill-track{background:#e9ecef;height:6px;border-radius:3px}.cv-infographic .skill-fill{background:linear-gradient(90deg,#f093fb,#f5576c);height:100%;border-radius:3px}',
8),

('Functional', 'functional', 'Skills-based layout organized by competency areas, great for career changers.', 'professional',
'<div class="cv-functional"><header><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p><div class="contact">{{contact_entries}}</div></header><section class="summary"><h2>Career Summary</h2><p>{{summary}}</p></section><section class="skill-groups"><h2>Core Competencies</h2>{{skill_group_entries}}</section><section class="experience"><h2>Employment History</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section></div>',
'.cv-functional{font-family:"Open Sans",sans-serif;max-width:800px;margin:0 auto;padding:35px;color:#333}.cv-functional header{text-align:center;margin-bottom:25px}.cv-functional header h1{font-size:26px;color:#2c3e50;margin-bottom:5px}.cv-functional header .title{font-size:15px;color:#3498db;margin-bottom:8px}.cv-functional header .contact{font-size:13px;color:#666}.cv-functional h2{font-size:15px;color:#2c3e50;border-bottom:2px solid #3498db;padding-bottom:5px;margin:20px 0 12px}.cv-functional .summary{font-size:14px;line-height:1.7}.cv-functional .skill-group{margin-bottom:18px}.cv-functional .skill-group-title{font-weight:bold;font-size:14px;color:#3498db;margin-bottom:5px}.cv-functional .skill-group-items{font-size:13px;line-height:1.7;color:#444}.cv-functional .experience-entry{margin-bottom:12px;display:flex;justify-content:space-between}.cv-functional .entry-title{font-weight:600;font-size:13px}.cv-functional .entry-company{font-size:12px;color:#666}.cv-functional .entry-date{font-size:12px;color:#999}',
9),

('Combination', 'combination', 'Hybrid layout combining chronological experience with skills highlights.', 'professional',
'<div class="cv-combination"><header><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p><div class="contact">{{contact_entries}}</div></header><section class="summary"><h2>Summary</h2><p>{{summary}}</p></section><section class="highlights"><h2>Key Qualifications</h2>{{highlight_entries}}</section><section class="experience"><h2>Professional Experience</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="skills"><h2>Skills</h2>{{skills_entries}}</section></div>',
'.cv-combination{font-family:"Roboto",sans-serif;max-width:800px;margin:0 auto;padding:35px;color:#333}.cv-combination header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #2196F3;padding-bottom:15px;margin-bottom:20px}.cv-combination header h1{font-size:26px;color:#1565C0;margin-bottom:3px}.cv-combination header .title{font-size:14px;color:#666}.cv-combination header .contact{font-size:12px;color:#777;text-align:right;line-height:1.8}.cv-combination h2{font-size:14px;color:#1565C0;text-transform:uppercase;letter-spacing:1px;margin:18px 0 10px;padding-bottom:5px;border-bottom:1px solid #e0e0e0}.cv-combination .summary{font-size:14px;line-height:1.7}.cv-combination .highlight-item{font-size:13px;padding:5px 0;padding-left:15px;position:relative}.cv-combination .highlight-item::before{content:"";position:absolute;left:0;top:12px;width:8px;height:8px;background:#2196F3;border-radius:50%}.cv-combination .experience-entry{margin-bottom:15px}.cv-combination .entry-header{display:flex;justify-content:space-between}.cv-combination .entry-title{font-weight:bold;font-size:14px}.cv-combination .entry-company{font-size:13px;color:#1565C0}.cv-combination .entry-date{font-size:12px;color:#999}.cv-combination .entry-description{font-size:13px;line-height:1.6;margin-top:4px}.cv-combination .skill-item{display:inline-block;background:#e3f2fd;color:#1565C0;padding:3px 10px;margin:3px;font-size:12px;border-radius:3px}',
10),

('Chronological', 'chronological', 'Timeline-focused layout emphasizing career progression and dates.', 'professional',
'<div class="cv-chronological"><header><h1>{{first_name}} {{last_name}}</h1><div class="contact">{{contact_entries}}</div></header><section class="summary"><h2>Objective</h2><p>{{summary}}</p></section><section class="experience"><h2>Work History</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="skills"><h2>Skills & Abilities</h2>{{skills_entries}}</section></div>',
'.cv-chronological{font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:35px;color:#222}.cv-chronological header{text-align:center;border-bottom:2px solid #222;padding-bottom:15px;margin-bottom:20px}.cv-chronological header h1{font-size:24px;text-transform:uppercase;letter-spacing:3px;margin-bottom:5px}.cv-chronological header .contact{font-size:13px;color:#555}.cv-chronological h2{font-size:14px;text-transform:uppercase;background:#222;color:#fff;padding:6px 12px;margin:18px 0 12px}.cv-chronological .summary{font-size:14px;line-height:1.7;margin-bottom:15px}.cv-chronological .experience-entry{margin-bottom:18px;display:grid;grid-template-columns:140px 1fr;gap:15px}.cv-chronological .entry-date{font-size:12px;color:#666;text-align:right;padding-top:2px}.cv-chronological .entry-title{font-weight:bold;font-size:15px}.cv-chronological .entry-company{font-size:13px;color:#444}.cv-chronological .entry-description{font-size:13px;line-height:1.6;margin-top:5px}.cv-chronological .education-entry{margin-bottom:12px}.cv-chronological .skill-item{font-size:13px;display:inline-block;margin-right:15px}',
11),

('Elegant', 'elegant', 'Refined typography with subtle gold accents for law and consulting.', 'executive',
'<div class="cv-elegant"><header><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p><div class="divider"></div><div class="contact">{{contact_entries}}</div></header><section class="summary"><h2>Profile</h2><p>{{summary}}</p></section><section class="experience"><h2>Experience</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="skills"><h2>Expertise</h2>{{skills_entries}}</section></div>',
'.cv-elegant{font-family:"Cormorant Garamond",Georgia,serif;max-width:780px;margin:0 auto;padding:45px 40px;color:#2c2c2c}.cv-elegant header{text-align:center;margin-bottom:30px}.cv-elegant header h1{font-size:34px;font-weight:400;letter-spacing:4px;margin-bottom:5px}.cv-elegant header .title{font-size:14px;letter-spacing:3px;color:#b8860b;text-transform:uppercase;margin-bottom:15px}.cv-elegant header .divider{width:60px;height:2px;background:#b8860b;margin:0 auto 15px}.cv-elegant header .contact{font-size:12px;color:#777;letter-spacing:1px}.cv-elegant h2{font-size:13px;text-transform:uppercase;letter-spacing:4px;color:#b8860b;text-align:center;margin:25px 0 15px;position:relative}.cv-elegant h2::after{content:"";display:block;width:40px;height:1px;background:#b8860b;margin:8px auto 0}.cv-elegant .summary{font-size:15px;line-height:1.9;text-align:center;color:#444;font-style:italic}.cv-elegant .experience-entry{margin-bottom:20px;text-align:center}.cv-elegant .entry-title{font-size:17px;font-weight:600}.cv-elegant .entry-company{font-size:14px;color:#b8860b}.cv-elegant .entry-date{font-size:12px;color:#999;letter-spacing:1px}.cv-elegant .entry-description{font-size:14px;line-height:1.7;color:#444;margin-top:5px;max-width:600px;margin-left:auto;margin-right:auto}.cv-elegant .skill-item{font-size:13px;color:#555;display:inline-block;margin:4px 12px;letter-spacing:1px}',
12),

('Bold', 'bold', 'Strong visual hierarchy with large headers and impactful design.', 'creative',
'<div class="cv-bold"><div class="header-block"><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p><div class="contact">{{contact_entries}}</div></div><section class="summary"><h2>About</h2><p>{{summary}}</p></section><section class="experience"><h2>Experience</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="skills"><h2>Skills</h2>{{skills_entries}}</section></div>',
'.cv-bold{font-family:"Impact","Arial Black",sans-serif;max-width:800px;margin:0 auto}.cv-bold .header-block{background:#e74c3c;color:#fff;padding:40px;text-align:center}.cv-bold .header-block h1{font-size:42px;letter-spacing:2px;margin-bottom:5px}.cv-bold .header-block .title{font-size:18px;font-family:"Arial",sans-serif;opacity:0.9;margin-bottom:10px}.cv-bold .header-block .contact{font-size:13px;font-family:"Arial",sans-serif;opacity:0.8}.cv-bold h2{font-size:22px;background:#2c3e50;color:#fff;padding:10px 20px;margin:0;letter-spacing:1px}.cv-bold .summary{padding:25px;font-family:"Arial",sans-serif;font-size:15px;line-height:1.7;color:#444}.cv-bold .experience-entry{padding:20px 25px;border-bottom:1px solid #eee;font-family:"Arial",sans-serif}.cv-bold .entry-title{font-size:18px;font-weight:700;color:#2c3e50}.cv-bold .entry-company{font-size:14px;color:#e74c3c}.cv-bold .entry-date{font-size:12px;color:#999}.cv-bold .entry-description{font-size:14px;line-height:1.6;color:#444;margin-top:5px}.cv-bold .education-entry{padding:15px 25px;font-family:"Arial",sans-serif}.cv-bold .skill-item{display:inline-block;background:#2c3e50;color:#fff;padding:6px 14px;margin:4px;font-family:"Arial",sans-serif;font-size:12px}',
13),

('Professional', 'professional', 'Balanced, ATS-friendly layout suitable for all industries.', 'professional',
'<div classcv-professional"><header><h1>{{first_name}} {{last_name}}</h1><div class="contact">{{contact_entries}}</div></header><section class="summary"><h2>Professional Summary</h2><p>{{summary}}</p></section><section class="experience"><h2>Experience</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="skills"><h2>Skills</h2>{{skills_entries}}</section><section class="certifications"><h2>Certifications</h2>{{certification_entries}}</section></div>',
'.cv-professional{font-family:Calibri,"Trebuchet MS",sans-serif;max-width:800px;margin:0 auto;padding:35px;color:#333}.cv-professional header{margin-bottom:20px}.cv-professional header h1{font-size:24px;color:#2c3e50;margin-bottom:5px}.cv-professional header .contact{font-size:13px;color:#666}.cv-professional h2{font-size:15px;color:#2c3e50;border-bottom:2px solid #2c3e50;padding-bottom:4px;margin:18px 0 10px}.cv-professional .summary{font-size:14px;line-height:1.7;margin-bottom:15px}.cv-professional .experience-entry{margin-bottom:15px}.cv-professional .entry-header{display:flex;justify-content:space-between;align-items:baseline}.cv-professional .entry-title{font-weight:bold;font-size:14px}.cv-professional .entry-company{font-size:13px;color:#2c3e50}.cv-professional .entry-date{font-size:12px;color:#888}.cv-professional .entry-description{font-size:13px;line-height:1.6;margin-top:4px}.cv-professional .education-entry{margin-bottom:10px}.cv-professional .skill-item{font-size:13px;display:inline-block;margin-right:12px;margin-bottom:4px}.cv-professional .certification-entry{font-size:13px;margin-bottom:5px}',
14),

('Fresh', 'fresh', 'Modern, vibrant design for young professionals and recent graduates.', 'minimal',
'<div class="cv-fresh"><div class="header-fresh"><div class="name-side"><h1>{{first_name}} {{last_name}}</h1><p class="title">{{job_title}}</p></div><div class="contact-side">{{contact_entries}}</div></div><section class="summary"><h2>Summary</h2><p>{{summary}}</p></section><section class="experience"><h2>Experience</h2>{{experience_entries}}</section><section class="education"><h2>Education</h2>{{education_entries}}</section><section class="skills"><h2>Skills</h2>{{skills_entries}}</section><section class="interests"><h2>Interests</h2>{{interest_entries}}</section></div>',
'.cv-fresh{font-family:"Nunito",sans-serif;max-width:800px;margin:0 auto;padding:0;overflow:hidden}.cv-fresh .header-fresh{background:linear-gradient(135deg,#43e97b 0%,#38f9d7 100%);padding:30px 35px;display:flex;justify-content:space-between;align-items:center}.cv-fresh .header-fresh h1{font-size:28px;font-weight:800;color:#fff;margin-bottom:3px}.cv-fresh .header-fresh .title{font-size:14px;color:rgba(255,255,255,0.85);font-weight:500}.cv-fresh .header-fresh .contact-side{font-size:12px;color:rgba(255,255,255,0.9);text-align:right;line-height:1.9}.cv-fresh h2{font-size:14px;font-weight:700;color:#43e97b;margin:20px 0 10px;padding-left:12px;border-left:4px solid #43e97b}.cv-fresh .summary{padding:0 35px;font-size:14px;line-height:1.7;color:#555}.cv-fresh .experience-entry{padding:12px 35px;margin-bottom:10px}.cv-fresh .entry-title{font-weight:700;font-size:15px;color:#333}.cv-fresh .entry-company{font-size:13px;color:#43e97b}.cv-fresh .entry-date{font-size:11px;color:#aaa}.cv-fresh .entry-description{font-size:13px;line-height:1.6;color:#555;margin-top:4px}.cv-fresh .education-entry{padding:8px 35px}.cv-fresh .skill-item{background:linear-gradient(135deg,#43e97b,#38f9d7);color:#fff;padding:4px 12px;margin:3px;border-radius:15px;font-size:12px;display:inline-block}.cv-fresh .interest-item{display:inline-block;font-size:13px;color:#666;margin:3px 10px}',
15);
